chore(LT-5853): [Lykke.Job.CandlesHistoryWriter] Update MessagePack t…
LykkeBusiness/Lykke.Job.CandlesHistoryWriter pull request #107
Opened 2024-10-28 10:26 UTC by lykke-vashetsin

…o 2.x version

2024-11-05 13:44 UTC, tarurar requested changes

2024-11-05 13:44 UTC, tarurar commented on Directory.Packages.props
> +    <PackageVersion Include="MessagePack" Version="2.5.187" />
You probably do not need direct dependency on MessagePack.

2024-11-05 13:44 UTC, tarurar commented on Directory.Packages.props
> +    <PackageVersion Include="Microsoft.Extensions.Logging.Debug" Version="8.0.1" />
Why do we need debug package?

2024-11-05 13:44 UTC, tarurar commented on src/Lykke.Job.CandleHistoryWriter.Repositories/Candles/SqlCandlesHistoryRepository.cs
> -            if (!rFactorDate.SameWeek(lastTradingDay, DayOfWeek.Monday))
How does rfactor task related to messagepack update?

2024-11-05 19:44 UTC, lykke-vashetsin commented on src/Lykke.Job.CandleHistoryWriter.Repositories/Candles/SqlCandlesHistoryRepository.cs
> -            if (!rFactorDate.SameWeek(lastTradingDay, DayOfWeek.Monday))
there was conflict namespaces

2024-11-05 19:45 UTC, lykke-vashetsin commented on Directory.Packages.props
> +    <PackageVersion Include="Microsoft.Extensions.Logging.Debug" Version="8.0.1" />
removed

2024-11-11 08:05 UTC, tarurar commented on src/Lykke.Job.CandleHistoryWriter.Repositories/Candles/SqlCandlesHistoryRepository.cs
> +            if (!CandlesHistoryWriter.Core.Domain.Candles.DateTimeExtensions.SameWeek(rFactorDate, lastTradingDay, DayOfWeek.Monday))
It looks like an extension method. Why can’t you just use it like `rFactorDate.SameWeel`?

2024-11-11 11:09 UTC, tarurar approved these changes

2024-11-11 11:13 UTC, merged